name: nexcampus_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  firebase_storage: ^13.4.5
  firebase_messaging: ^16.3.0
  firebase_analytics: ^12.4.2
  firebase_crashlytics: ^5.2.3

  # Authentication
  google_sign_in: ^6.1.4

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.2.1
  equatable: ^2.0.8

  # Networking
  dio: ^5.9.0
  http: ^1.6.0

  # Storage
  shared_preferences: ^2.5.5
  path_provider: ^2.1.5

  # File & Image
  image_picker: ^1.2.3
  file_picker: ^11.0.2
  open_filex: ^4.5.0
  flutter_file_dialog: ^3.0.2

  # Cloudinary
  cloudinary_public: ^0.23.1

  # UI
  google_fonts: ^8.2.0
  percent_indicator: ^4.2.5
  table_calendar: ^3.2.0
  qr_flutter: ^4.1.0

  # Maps
  flutter_map: ^8.3.1
  latlong2: ^0.10.1

  # Web & URL
  webview_flutter: ^4.14.1
  url_launcher: ^6.3.2

  # PDF
  syncfusion_flutter_pdfviewer: ^29.2.11

  # Utilities
  intl: ^0.20.3
  device_info_plus: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/App_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/App_icon.png
    - assets/images/google_logo.png
    - assets/images/mbman_app_icon.png