// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMn-fE9yYkE8RSTufTZ84bpOL-VtF2isQ',
    appId: '1:1069670402553:web:499a37f1c302184e62d528',
    messagingSenderId: '1069670402553',
    projectId: 'nexcampus-a33c9',
    authDomain: 'nexcampus-a33c9.firebaseapp.com',
    storageBucket: 'nexcampus-a33c9.firebasestorage.app',
    measurementId: 'G-5XZ6YRZFNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiHiGuKxN4JqjCnYkwES7u6IKGCXoOgco',
    appId: '1:1069670402553:android:2e79b800b39de62362d528',
    messagingSenderId: '1069670402553',
    projectId: 'nexcampus-a33c9',
    storageBucket: 'nexcampus-a33c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1IsD-rQPMF2lPtb2RfQ-q2PUJYGfNRkE',
    appId: '1:1069670402553:ios:afd2f64514eb998e62d528',
    messagingSenderId: '1069670402553',
    projectId: 'nexcampus-a33c9',
    storageBucket: 'nexcampus-a33c9.firebasestorage.app',
    androidClientId: '1069670402553-u6f508om29glel5rhhtmp1od6e5bl59o.apps.googleusercontent.com',
    iosClientId: '1069670402553-hivr066ra8glsjn0djollf76nae7beog.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexcampusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1IsD-rQPMF2lPtb2RfQ-q2PUJYGfNRkE',
    appId: '1:1069670402553:ios:afd2f64514eb998e62d528',
    messagingSenderId: '1069670402553',
    projectId: 'nexcampus-a33c9',
    storageBucket: 'nexcampus-a33c9.firebasestorage.app',
    androidClientId: '1069670402553-u6f508om29glel5rhhtmp1od6e5bl59o.apps.googleusercontent.com',
    iosClientId: '1069670402553-hivr066ra8glsjn0djollf76nae7beog.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexcampusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMn-fE9yYkE8RSTufTZ84bpOL-VtF2isQ',
    appId: '1:1069670402553:web:a755002215e6f1cb62d528',
    messagingSenderId: '1069670402553',
    projectId: 'nexcampus-a33c9',
    authDomain: 'nexcampus-a33c9.firebaseapp.com',
    storageBucket: 'nexcampus-a33c9.firebasestorage.app',
    measurementId: 'G-9QRKB3VYXY',
  );
}
