// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEdsc7LhDZf46r8yprUIq3D5wdyqVEPZ0',
    appId: '1:1023420981418:web:7be36d95229c473b2df0d3',
    messagingSenderId: '1023420981418',
    projectId: 'nex-campus-a6bda',
    authDomain: 'nex-campus-a6bda.firebaseapp.com',
    storageBucket: 'nex-campus-a6bda.firebasestorage.app',
    measurementId: 'G-E633NB50PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_lbtIluZWzxTiRSfsjkH2VSWOv22z3bo',
    appId: '1:1023420981418:android:54f72681bb564ba32df0d3',
    messagingSenderId: '1023420981418',
    projectId: 'nex-campus-a6bda',
    storageBucket: 'nex-campus-a6bda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBVtkpPO0AfPcaHFQ-wznge1xMjF-p3v8',
    appId: '1:1023420981418:ios:56b5fb69290491a02df0d3',
    messagingSenderId: '1023420981418',
    projectId: 'nex-campus-a6bda',
    storageBucket: 'nex-campus-a6bda.firebasestorage.app',
    iosBundleId: 'com.example.nexcampusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBVtkpPO0AfPcaHFQ-wznge1xMjF-p3v8',
    appId: '1:1023420981418:ios:56b5fb69290491a02df0d3',
    messagingSenderId: '1023420981418',
    projectId: 'nex-campus-a6bda',
    storageBucket: 'nex-campus-a6bda.firebasestorage.app',
    iosBundleId: 'com.example.nexcampusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEdsc7LhDZf46r8yprUIq3D5wdyqVEPZ0',
    appId: '1:1023420981418:web:1c7330dc1c9991bb2df0d3',
    messagingSenderId: '1023420981418',
    projectId: 'nex-campus-a6bda',
    authDomain: 'nex-campus-a6bda.firebaseapp.com',
    storageBucket: 'nex-campus-a6bda.firebasestorage.app',
    measurementId: 'G-6MZWDZ5M0C',
  );
}
